### ISSUE TITLE
Double Fast Weapons cause no consume stamina. (and other issue)

### ISSUE THREAD

**Issue by Petriell0** [CCr4ft3r/actions-of-stamina#10]
if you use two fast weapons (daggers) with a fast atack speed, the mod will ignore the stamina consumption of atacks.

- knight armor
- simple swords

other minor issue.
better combat (auto swing) bypass stamina limits (makes the player can continue attacking even when he has already zeroed his stamina.)
- better combat

**Comment by CCr4ft3r** [comment]
Second issue is a duplicate of #1

**Comment by CCr4ft3r** [comment]
I have changed the multipilier for attacks based on the attack speed to being base on the attack damage of the weapon
