### ISSUE TITLE
Allow third party sharing in Curse Forge

### ISSUE THREAD

**Issue by Kevadroz** [CCr4ft3r/actions-of-stamina#13]
This would allow third party launchers (Prism Launcher, GDLauncher) to download the mod without issues.
Also allows the usage of Curse Maven.

**Comment by Churchexe** [comment]
I can't speak for prism, but GD launcher already can download the mod without issues. Are you referring to the popup window thing they have to do to get past the weird curseforge API restrictions they added?

**Comment by Kevadroz** [comment]
Yeah idk how 'allowed' is what GDLauncher does but it does block Prism Launcher (without giving it a key from the curse launcher) and curse maven.
Changing this is as easy as going into the project settings and switching a toggle somewhere.

**Comment by CCr4ft3r** [comment]
Sorry, but I will not allow third parties sharing, since it's has some drawbacks for devs
