### ISSUE TITLE
[Suggestion] Wall-Jump! integration

### ISSUE THREAD

**Issue by aurora-hope** [CCr4ft3r/actions-of-stamina#6]
https://www.curseforge.com/minecraft/mc-mods/wall-jump
This mod's ability to cling to walls and jump off of them could potentially use feathers. Maybe draining stamina slowly as you cling to walls, and then using a chunk of it when the player executes a wall jump?

**Comment by CCr4ft3r** [comment]
Since Wall-Jump provides a config option that let you control how long you can cling on walls I will only add support for wall jumps itself.

**Comment by CCr4ft3r** [comment]
Done. Will be included in the next feature update
